name: generate animation

on:
  # Executa a cada 24 horas
  schedule:
    - cron: "0 */24 * * *"

  # Permite executar manualmente
  workflow_dispatch:

  # Executa quando houver push na main
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: brunokawan
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%23F97316&color_dots=%23161b22,%237C2D12,%23C2410C,%23EA580C,%23FB923C
            dist/github-contribution-grid-snake-dark.svg?color_snake=%23F97316&color_dots=%23161b22,%237C2D12,%23C2410C,%23EA580C,%23FB923C
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Snake to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
